name: data_store
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  csv:
  yaml: ^3.1.0
  excel: ^2.0.0-null-safety-3
  meta: ^1.7.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner:
  freezed:
  freezed_annotation:
  json_serializable: